-- Space-scoped label catalog. Keep the first spelling used in each space, while
-- enforcing case-insensitive uniqueness through normalized_name.
ALTER TABLE issue_labels RENAME TO issue_labels_legacy;
DROP INDEX idx_issue_labels_issue;

CREATE TABLE labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    normalized_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_labels_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT uk_labels_space_normalized UNIQUE (space_id, normalized_name)
);

CREATE INDEX idx_labels_space_active ON labels (space_id, deleted_at);

INSERT INTO labels (space_id, name, normalized_name, created_at)
SELECT i.space_id,
       MIN(il.label),
       LOWER(BTRIM(il.label)),
       CURRENT_TIMESTAMP
FROM issue_labels_legacy il
JOIN issues i ON i.id = il.issue_id
WHERE BTRIM(il.label) <> ''
GROUP BY i.space_id, LOWER(BTRIM(il.label));

CREATE TABLE issue_labels (
    issue_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    CONSTRAINT pk_issue_labels PRIMARY KEY (issue_id, label_id),
    CONSTRAINT fk_issue_labels_issue FOREIGN KEY (issue_id) REFERENCES issues (id),
    CONSTRAINT fk_issue_labels_label FOREIGN KEY (label_id) REFERENCES labels (id)
);

INSERT INTO issue_labels (issue_id, label_id)
SELECT DISTINCT il.issue_id, l.id
FROM issue_labels_legacy il
JOIN issues i ON i.id = il.issue_id
JOIN labels l
  ON l.space_id = i.space_id
 AND l.normalized_name = LOWER(BTRIM(il.label))
WHERE BTRIM(il.label) <> '';

CREATE INDEX idx_issue_labels_issue ON issue_labels (issue_id);
CREATE INDEX idx_issue_labels_label ON issue_labels (label_id);
DROP TABLE issue_labels_legacy;

-- Historical sprint membership and estimates. These rows remain after issues
-- are carried over so completed-sprint reporting does not depend on sprint_id.
CREATE TABLE sprint_issue_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sprint_id BIGINT NOT NULL,
    issue_id BIGINT NOT NULL,
    issue_key VARCHAR(30) NOT NULL,
    issue_type VARCHAR(20) NOT NULL,
    initial_scope BOOLEAN NOT NULL,
    points_at_start INTEGER,
    points_at_end INTEGER,
    status_at_end VARCHAR(20),
    outcome VARCHAR(20),
    added_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    removed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_sprint_history_sprint FOREIGN KEY (sprint_id) REFERENCES sprints (id),
    CONSTRAINT uk_sprint_history_sprint_issue UNIQUE (sprint_id, issue_id)
);

CREATE INDEX idx_sprint_history_sprint ON sprint_issue_history (sprint_id);
CREATE INDEX idx_sprint_history_issue ON sprint_issue_history (issue_id);

ALTER TABLE sprints ADD COLUMN initial_committed_points INTEGER;
ALTER TABLE sprints ADD COLUMN initial_completed_points INTEGER;
ALTER TABLE sprints ADD COLUMN final_scope_points INTEGER;
ALTER TABLE sprints ADD COLUMN completed_points INTEGER;
ALTER TABLE sprints ADD COLUMN initial_issue_count INTEGER;
ALTER TABLE sprints ADD COLUMN completed_issue_count INTEGER;
ALTER TABLE sprints ADD COLUMN final_issue_count INTEGER;
ALTER TABLE sprints ADD COLUMN unestimated_issue_count INTEGER;
