-- Initial schema aligned with JPA entities (PostgreSQL)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(100),
    avatar_color VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    space_key VARCHAR(20) NOT NULL,
    color VARCHAR(30),
    owner_id BIGINT,
    issue_counter INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_spaces_space_key UNIQUE (space_key),
    CONSTRAINT fk_spaces_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_groups_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE space_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_space_members_space_user UNIQUE (space_id, user_id),
    CONSTRAINT fk_space_members_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_space_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES user_groups (id),
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE space_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    added_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_space_groups_space_group UNIQUE (space_id, group_id),
    CONSTRAINT fk_space_groups_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_space_groups_group FOREIGN KEY (group_id) REFERENCES user_groups (id)
);

CREATE TABLE sprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    goal TEXT,
    start_date DATE,
    end_date DATE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sprints_space FOREIGN KEY (space_id) REFERENCES spaces (id)
);

CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_key VARCHAR(30) NOT NULL,
    space_id BIGINT NOT NULL,
    sprint_id BIGINT,
    parent_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    issue_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20),
    assignee_id BIGINT,
    reporter_id BIGINT,
    story_points INTEGER,
    start_date DATE,
    due_date DATE,
    issue_order INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_issues_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_issues_sprint FOREIGN KEY (sprint_id) REFERENCES sprints (id),
    CONSTRAINT fk_issues_parent FOREIGN KEY (parent_id) REFERENCES issues (id),
    CONSTRAINT fk_issues_assignee FOREIGN KEY (assignee_id) REFERENCES users (id),
    CONSTRAINT fk_issues_reporter FOREIGN KEY (reporter_id) REFERENCES users (id)
);

CREATE INDEX idx_issue_space ON issues (space_id);
CREATE INDEX idx_issue_sprint ON issues (sprint_id);
CREATE INDEX idx_issue_parent ON issues (parent_id);
CREATE UNIQUE INDEX idx_issue_key ON issues (issue_key);

-- @ElementCollection on Issue.labels (bag; no PK required by Hibernate)
CREATE TABLE issue_labels (
    issue_id BIGINT NOT NULL,
    label VARCHAR(50) NOT NULL,
    CONSTRAINT fk_issue_labels_issue FOREIGN KEY (issue_id) REFERENCES issues (id)
);

CREATE INDEX idx_issue_labels_issue ON issue_labels (issue_id);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id) REFERENCES issues (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_comment_issue ON comments (issue_id);
