"""Domain corpus for the seed generator.

Everything here is hand-written product content for two fictional fintech teams.
The generator in generate_seed.py stitches it into a time-ordered simulation, so
the value of this file is coherence: an epic's children, its bugs, its pull
request titles and its review comments all talk about the same subsystem.

Placeholders available in templated strings:
  {component}  a subsystem noun owned by the epic (e.g. "settlement-worker")
  {service}    the deployable the epic lives in
  {actor}      a teammate's display name
  {key}        an issue key such as PAY-214
"""

# --- people ---------------------------------------------------------------
# discipline drives assignment affinity: backend epics land on BE engineers,
# QA files most bugs, PM/EM file most stories.

PEOPLE = [
    ("emma.reyes",   "Emma Reyes",      "em",       "#6366F1"),
    ("noah.baptiste", "Noah Baptiste",  "tl-pay",   "#0EA5E9"),
    ("priya.raman",  "Priya Raman",     "tl-mer",   "#8B5CF6"),
    ("kenji.watanabe", "Kenji Watanabe", "be",      "#10B981"),
    ("lucia.ferrari", "Lucia Ferrari",  "be",       "#F59E0B"),
    ("omar.haddad",  "Omar Haddad",     "be",       "#EF4444"),
    ("sofia.lindqvist", "Sofia Lindqvist", "fe",    "#EC4899"),
    ("dan.okafor",   "Dan Okafor",      "fe",       "#14B8A6"),
    ("mei.chen",     "Mei Chen",        "fe",       "#A855F7"),
    ("tomas.novak",  "Tomas Novak",     "sre",      "#F97316"),
    ("aisha.bello",  "Aisha Bello",     "qa",       "#22C55E"),
    ("greg.thornton", "Greg Thornton",  "qa",       "#3B82F6"),
    ("hannah.ross",  "Hannah Ross",     "pm",       "#D946EF"),
    ("victor.almeida", "Victor Almeida", "design",  "#64748B"),
]

# --- spaces ---------------------------------------------------------------

SPACES = [
    {
        "key": "PAY",
        "name": "Payments Platform",
        "color": "#0052CC",
        "lead": "tl-pay",
        "disciplines": ["be", "sre"],
        "repos": [("acme-fintech", "payments-core"), ("acme-fintech", "ledger-service")],
        "service": "payments-core",
    },
    {
        "key": "MER",
        "name": "Merchant Portal",
        "color": "#8B5CF6",
        "lead": "tl-mer",
        "disciplines": ["fe", "be", "design"],
        "repos": [("acme-fintech", "merchant-portal"), ("acme-fintech", "portal-bff")],
        "service": "merchant-portal",
    },
]

# --- epics ----------------------------------------------------------------
# Each epic: title, goal, discipline that owns it, components it touches, and a
# pool of concrete child work items (type, title, and a description body).

EPICS = {
    "PAY": [
        {
            "title": "Double-entry ledger migration",
            "goal": "Replace the single-row balance table with an append-only double-entry ledger so every balance is reconstructable from journal entries.",
            "why": "Finance cannot currently explain a balance without reading application logs. Two audit findings in Q1 traced back to this.",
            "metric": "100% of merchant balances reproducible from journal entries; reconciliation job runs green for 14 consecutive days.",
            "discipline": "be",
            "components": ["ledger-service", "journal-writer", "balance-projector", "reconciliation-job"],
            "children": [
                ("story", "Model journal entries and postings",
                 "As the ledger service I need an append-only `journal_entry` / `posting` model so that every balance change is attributable to a balanced transaction.\n\nAcceptance criteria:\n- A journal entry holds 2..n postings whose signed amounts sum to zero per currency.\n- Entries are immutable once written; corrections are new reversing entries.\n- Each entry carries an idempotency key sourced from the originating payment event.\n\nOut of scope: the read-side projection (tracked separately)."),
                ("story", "Build balance projector from journal stream",
                 "As a merchant I want my available balance to reflect settled postings within seconds so that the dashboard is trustworthy.\n\nAcceptance criteria:\n- Projector consumes the journal topic and maintains `balance_snapshot` per (merchant, currency).\n- Projection lag exposed as a gauge; alert at >30s sustained.\n- Rebuilding from offset 0 produces byte-identical snapshots."),
                ("task", "Dual-write payments to legacy balances and journal",
                 "Write to both stores behind the `ledger.dual_write` flag so we can compare before cutting over.\n\nScope: write path only. Comparison tooling is a separate ticket."),
                ("task", "Nightly reconciliation between legacy balances and journal",
                 "Batch job compares `merchant_balance.amount` against the projected journal balance and emits a per-merchant diff report.\n\nAny non-zero diff pages the on-call during cutover week only."),
                ("task", "Backfill 18 months of historical payments into journal",
                 "Chunked backfill keyed on payment id, resumable, rate-limited to keep replica lag under 5s. Estimated 41M rows."),
                ("story", "Expose ledger statement API for finance export",
                 "As a finance analyst I want a paginated statement endpoint per merchant and date range so I can reconcile against the bank file without a DB export.\n\nAcceptance criteria:\n- Cursor pagination, stable ordering by (booked_at, entry_id).\n- CSV and JSON representations.\n- Response includes opening and closing balance for the window."),
                ("task", "Cut over reads to the projected balance",
                 "Flip `ledger.read_from_projection` per merchant cohort: internal test merchants, then 1%, 10%, 50%, 100%. Each step holds for 24h."),
                ("task", "Decommission legacy balance write path",
                 "Remove dual-write, drop the flag, and archive `merchant_balance` to cold storage. Blocked until reconciliation is clean for two weeks."),
                ("story", "Support reversing entries for corrections",
                 "As an operations agent I need to reverse a mis-booked entry so that the ledger stays append-only while the balance is corrected.\n\nAcceptance criteria:\n- Reversal references the original entry id and is itself immutable.\n- Reversing an already-reversed entry is rejected.\n- Reversals require an ops reason code, surfaced in the statement export."),
                ("task", "Load test journal writer at 5x peak throughput",
                 "Peak is currently 840 writes/s. Verify p99 write latency stays under 40ms at 4200 writes/s with the projector running."),
            ],
        },
        {
            "title": "3-D Secure 2 / SCA compliance",
            "goal": "Support 3DS2 authentication end to end so European card volume stays compliant with PSD2 strong customer authentication.",
            "why": "Issuers begin declining non-SCA transactions on the regulator's deadline. Roughly 34% of card volume is in scope.",
            "metric": "SCA-eligible volume authenticated >99%; frictionless rate above 70%; no increase in overall decline rate.",
            "discipline": "be",
            "components": ["auth-orchestrator", "3ds-adapter", "challenge-service", "exemption-engine"],
            "children": [
                ("story", "Integrate 3DS2 authentication request with card scheme adapter",
                 "As the payment orchestrator I need to send an AReq and interpret the ARes so that eligible transactions are authenticated before authorization.\n\nAcceptance criteria:\n- AReq built from the device fingerprint, cardholder data and merchant risk indicators.\n- Frictionless approvals continue straight to authorization.\n- Challenge responses return a redirect payload to the merchant."),
                ("story", "Render challenge flow in hosted checkout",
                 "As a cardholder I want the issuer challenge to appear inside checkout so I am not bounced to an unfamiliar page.\n\nAcceptance criteria:\n- Challenge iframe sized per the scheme's five supported dimensions.\n- Timeout after 10 minutes returns a typed `authentication_timeout` error.\n- Works in Safari with third-party cookies blocked."),
                ("task", "Implement SCA exemption engine (TRA, low value, recurring)",
                 "Evaluate exemptions in priority order and record which one was applied, because acquirer reporting requires the exemption reason per transaction."),
                ("task", "Persist authentication artefacts for chargeback defence",
                 "Store the CAVV, ECI and DS transaction id against the payment. These are the evidence fields the scheme asks for during liability shift disputes."),
                ("story", "Fall back to 3DS1 for issuers that have not migrated",
                 "As a merchant I want transactions to still authenticate when the issuer only supports 3DS1 so I do not lose the sale.\n\nAcceptance criteria:\n- Directory server version lookup cached for 24h.\n- Fallback decision recorded on the payment.\n- Fallback rate exposed per issuer BIN range."),
                ("task", "Certify with scheme test suite (Visa and Mastercard)",
                 "Run the mandated certification scripts in the scheme sandbox and file the results. Both schemes must pass before production credentials are issued."),
                ("task", "Add SCA decision audit log",
                 "Every authentication decision writes an immutable record: eligibility, exemption considered, exemption applied, outcome. Retained seven years."),
                ("story", "Expose authentication status on the payment API",
                 "As an integrating merchant I want to read the authentication outcome from the payment resource so I can decide whether to retry.\n\nAcceptance criteria:\n- `authentication.status` is one of not_required, frictionless, challenged, failed.\n- Liability shift indicator exposed.\n- Documented in the public OpenAPI spec."),
                ("task", "Shadow-run exemption engine against production traffic",
                 "Evaluate exemptions without acting on them for two weeks and compare predicted friction against actual issuer behaviour."),
            ],
        },
        {
            "title": "Payout scheduling engine",
            "goal": "Move payouts from a fixed nightly cron to a scheduling engine that honours per-merchant payout policy, banking calendars and holds.",
            "why": "Merchants on weekly terms are being paid on the wrong day around public holidays, generating a steady stream of support tickets.",
            "metric": "Payout date accuracy 100% against contract terms; support tickets tagged 'payout timing' down 80%.",
            "discipline": "be",
            "components": ["payout-scheduler", "banking-calendar", "payout-worker", "hold-service"],
            "children": [
                ("story", "Define per-merchant payout policy",
                 "As an account manager I want to configure payout frequency, delay and minimum amount per merchant so terms match the signed contract.\n\nAcceptance criteria:\n- Frequency: daily, weekly (with weekday), monthly (with day of month).\n- Rolling reserve delay in days.\n- Changes are versioned and take effect from the next unscheduled payout."),
                ("task", "Import banking calendars for supported corridors",
                 "SEPA, FPS, ACH and BACS calendars including regional holidays. Source refreshed annually; a stale calendar must fail loudly rather than assume a business day."),
                ("story", "Schedule payouts against the banking calendar",
                 "As a merchant I want my payout to land on the next business day when my scheduled date is a holiday so the money arrives predictably.\n\nAcceptance criteria:\n- Non-business days roll forward, never backward.\n- Cut-off time per corridor respected in the corridor's local timezone.\n- Scheduled date is visible in the portal before the payout executes."),
                ("task", "Idempotent payout execution worker",
                 "A payout must never be sent twice even if the worker crashes mid-flight. Key on (merchant, scheduled_date, sequence)."),
                ("story", "Place and release payout holds",
                 "As a risk analyst I want to hold a merchant's payouts so funds stop moving while an investigation is open.\n\nAcceptance criteria:\n- Hold blocks scheduling, not accrual.\n- Releasing a hold reschedules to the next eligible date.\n- Every hold and release is attributed to an analyst with a reason."),
                ("task", "Emit payout lifecycle events to the notification topic",
                 "scheduled, submitted, paid, returned, failed. The portal notification centre consumes these."),
                ("task", "Migrate existing merchants off the nightly cron",
                 "Backfill a policy row for every active merchant derived from their current behaviour, then disable the cron. Requires a dry-run diff sign-off from finance."),
                ("story", "Handle returned payouts and bank rejections",
                 "As operations I need returned payouts to be visible and re-attemptable so funds do not sit in limbo.\n\nAcceptance criteria:\n- Return reason codes mapped to human-readable causes.\n- Returned funds credited back to the merchant balance via a reversing entry.\n- Merchant notified with the corrective action needed."),
            ],
        },
        {
            "title": "Refund and chargeback automation",
            "goal": "Automate the dispute lifecycle from network notification through evidence submission so agents only touch cases that need judgement.",
            "why": "Dispute volume grew 3x year on year while the ops team stayed the same size. Response deadlines are being missed.",
            "metric": "Evidence submitted within SLA on 99% of disputes; manual touches per dispute below 0.4.",
            "discipline": "be",
            "components": ["dispute-service", "evidence-builder", "network-webhook", "refund-worker"],
            "children": [
                ("story", "Ingest dispute notifications from card networks",
                 "As the dispute service I need to consume network webhooks so a case exists the moment the issuer raises it.\n\nAcceptance criteria:\n- Signature verified per network.\n- Duplicate notifications collapse onto one case.\n- Unknown reason codes create a case flagged for manual triage rather than failing."),
                ("task", "Model dispute lifecycle states and transitions",
                 "needs_response, under_review, won, lost, expired. Illegal transitions rejected at the service boundary, not by convention."),
                ("story", "Auto-assemble evidence packets",
                 "As an ops agent I want the evidence packet pre-filled so I only review rather than gather.\n\nAcceptance criteria:\n- Packet pulls the AVS/CVV result, 3DS artefacts, delivery confirmation and prior refund history.\n- Missing mandatory fields are listed explicitly before submission.\n- Packet renders to the PDF layout each network requires."),
                ("task", "Deadline tracking with escalating reminders",
                 "T-7, T-3 and T-1 day reminders to the assigned agent, then to the ops lead. Deadlines are network-specific and in the network's timezone."),
                ("story", "Partial refunds against the ledger",
                 "As a merchant I want to refund part of a payment so I can resolve a dispute without giving back the full amount.\n\nAcceptance criteria:\n- Sum of refunds can never exceed the captured amount.\n- Each refund books a reversing journal entry.\n- Currency and FX rate of the original capture are preserved."),
                ("task", "Represent-ment flow for won-then-reopened cases",
                 "Networks can reopen a won case as pre-arbitration. The case must reopen with history intact rather than a new case being created."),
                ("task", "Dispute metrics dashboard for the ops lead",
                 "Win rate by reason code, time to submit, and cases at risk of missing SLA."),
                ("story", "Notify merchants when a dispute is raised",
                 "As a merchant I want to know a dispute exists while I can still influence it.\n\nAcceptance criteria:\n- Notification sent within 5 minutes of case creation.\n- Includes the deadline and what evidence would help.\n- Suppressed for merchants whose contract makes us liable."),
            ],
        },
        {
            "title": "Multi-currency settlement",
            "goal": "Settle in the merchant's chosen currency with transparent FX, rather than forcing everyone into their acquiring currency.",
            "why": "Three enterprise deals in the pipeline are blocked on settling in a currency we do not support.",
            "metric": "Settlement supported in 12 currencies; FX margin reported per settlement batch to the cent.",
            "discipline": "be",
            "components": ["fx-service", "settlement-batcher", "rate-cache", "corridor-config"],
            "children": [
                ("story", "Quote and lock FX rates for settlement batches",
                 "As the settlement batcher I need a locked rate for the batch so the amount we promise is the amount we send.\n\nAcceptance criteria:\n- Rate locked at batch creation and stored with the batch.\n- Quote expiry rejects settlement rather than silently re-quoting.\n- Provider rate plus our margin recorded separately."),
                ("task", "Rate provider client with failover to secondary feed",
                 "Primary feed outage must not stop settlement. Failover switches feeds and tags the batch with the source used."),
                ("story", "Configure settlement currency per merchant account",
                 "As an account manager I want to set which currency a merchant settles in so we can close multi-region deals.\n\nAcceptance criteria:\n- Settlement currency validated against the corridor's supported list.\n- Changing it takes effect from the next batch, never mid-batch.\n- Historical batches keep the currency they settled in."),
                ("task", "Report FX margin per settlement batch",
                 "Finance needs provider rate, applied rate, margin amount and margin basis points per batch, exportable as CSV."),
                ("task", "Round-half-even money arithmetic across the settlement path",
                 "Replace floating point arithmetic with minor-unit integers. Currencies with zero and three decimal places must be handled, not assumed to be two."),
                ("story", "Show settlement currency and rate in the portal",
                 "As a merchant I want to see the rate applied to my settlement so I can reconcile against my bank statement.\n\nAcceptance criteria:\n- Rate, source currency amount and settled amount all shown.\n- Available on the settlement detail page and in the CSV export."),
            ],
        },
        {
            "title": "Gateway resiliency and failover",
            "goal": "Survive an acquirer or region outage without dropping authorization traffic.",
            "why": "A 47-minute acquirer outage last quarter cost an estimated 1.2M in failed authorizations because we had no automatic failover.",
            "metric": "Authorization success rate stays above 98% during a simulated acquirer outage; failover completes in under 30 seconds.",
            "discipline": "sre",
            "components": ["gateway-router", "health-prober", "circuit-breaker", "retry-queue"],
            "children": [
                ("story", "Route authorizations across multiple acquirers",
                 "As the gateway I need to choose an acquirer per transaction so traffic can shift when one degrades.\n\nAcceptance criteria:\n- Routing weights configurable per card scheme and country.\n- Routing decision recorded on the payment for later analysis.\n- Weight changes apply without a deploy."),
                ("task", "Health probing and circuit breaking per acquirer",
                 "Open the breaker on error rate or latency breach, half-open probe every 15s. Breaker state must be observable, not inferred from logs."),
                ("task", "Retry queue for transient authorization failures",
                 "Bounded retries with jitter for network-level failures only. A decline is never retried — that is the issuer's answer."),
                ("story", "Fail over automatically on acquirer degradation",
                 "As the on-call engineer I want traffic to shift away from a degraded acquirer without me intervening.\n\nAcceptance criteria:\n- Failover triggers within 30s of breach.\n- Page fires on failover with the reason.\n- Manual override to pin traffic is available."),
                ("task", "Game day: simulate a full acquirer outage in staging",
                 "Inject failure at the acquirer boundary and verify the runbook against reality. Findings become tickets."),
                ("task", "Publish SLOs and error budget for the authorization path",
                 "Availability and latency SLOs with burn-rate alerting at 2x and 14x."),
                ("story", "Give operations a routing control panel",
                 "As an operations lead I want to shift routing weights during an incident so I do not need an engineer to run a script.\n\nAcceptance criteria:\n- Changes are audited with actor and reason.\n- A confirmation step shows the traffic impact before applying.\n- Changes propagate to all gateway instances within 10 seconds."),
            ],
        },
        {
            "title": "Observability and SLO instrumentation",
            "goal": "Make payment failures diagnosable in minutes by threading trace context and standardising failure taxonomy.",
            "why": "Mean time to identify on payment incidents is 38 minutes, almost all of it spent working out which hop failed.",
            "metric": "MTTI under 10 minutes; every payment failure carries a typed reason code.",
            "discipline": "sre",
            "components": ["tracing", "metrics-pipeline", "log-enrichment", "alerting"],
            "children": [
                ("task", "Propagate trace context across the whole payment path",
                 "W3C trace context through the gateway, orchestrator, ledger and payout worker, including across the Kafka hop where it is currently dropped."),
                ("story", "Standardise failure reason codes",
                 "As an on-call engineer I want a typed reason on every failure so I can group incidents without reading free text.\n\nAcceptance criteria:\n- Closed enum, documented, versioned.\n- Every failure path maps to exactly one code.\n- Untyped failures surface as `unknown` on a dashboard we actually watch."),
                ("task", "Payment funnel dashboard from initiation to settlement",
                 "Volume and drop-off at each stage with the ability to break down by acquirer, scheme and country."),
                ("task", "Alert on authorization success rate by acquirer",
                 "Alert on a rate drop relative to the acquirer's own baseline. A global threshold hides single-acquirer degradation."),
                ("task", "Sample and store failed authorization payloads for 7 days",
                 "Card data redacted at capture, not at read. Access is audited."),
                ("task", "Runbook for the top five payment incident classes",
                 "Each runbook names the dashboard, the first query to run, and the rollback lever."),
            ],
        },
    ],
    "MER": [
        {
            "title": "Merchant onboarding and KYC",
            "goal": "Take a merchant from signup to first payment without a human in the loop for the standard-risk path.",
            "why": "Median time to first payment is 6 days, and 41% of signups abandon before completing verification.",
            "metric": "Median time to first payment under 30 minutes; standard-risk applications fully automated.",
            "discipline": "fe",
            "components": ["onboarding-wizard", "kyc-adapter", "document-upload", "application-state"],
            "children": [
                ("story", "Multi-step onboarding wizard with resumable progress",
                 "As a new merchant I want to leave the application and come back without losing my place so I can gather documents at my own pace.\n\nAcceptance criteria:\n- Progress saved on each step transition, not only on submit.\n- Resume link emailed after 24h of inactivity.\n- Browser back navigates steps rather than leaving the flow."),
                ("story", "Business identity verification against the registry",
                 "As a compliance officer I want company details verified against the official registry so we do not onboard shell entities.\n\nAcceptance criteria:\n- Company number, legal name and address checked.\n- Mismatches surface the specific field that disagreed.\n- Registry outage puts the application in manual review rather than rejecting it."),
                ("task", "Document upload with client-side validation",
                 "Accept PDF, JPEG and PNG up to 10MB. Reject unreadable scans before upload rather than after review."),
                ("story", "Beneficial ownership collection",
                 "As a compliance officer I need every owner above 25% recorded so the file satisfies our KYC obligations.\n\nAcceptance criteria:\n- Ownership percentages must total no more than 100.\n- Each owner needs an identity document.\n- Corporate owners recurse one level."),
                ("task", "Application status tracker with expected timelines",
                 "Show which stage the application is in and what happens next. 'Pending' with no context is the single biggest driver of onboarding support contacts."),
                ("story", "Automated decisioning for standard-risk applications",
                 "As the platform I want to approve low-risk applications automatically so merchants can transact immediately.\n\nAcceptance criteria:\n- Risk score computed from registry, sanctions and device signals.\n- Auto-approve, auto-decline and manual review bands are configurable.\n- Every automated decision is explainable in the audit trail."),
                ("task", "Sanctions and PEP screening adapter",
                 "Screen at application and re-screen daily thereafter. A new hit on an active merchant raises a review case."),
                ("task", "Email and SMS reminders for stalled applications",
                 "Nudge at 24h, 72h and 7 days, then stop. Reminder cadence configurable without a deploy."),
                ("story", "Let merchants correct a rejected document",
                 "As a merchant I want to know exactly which document failed and why so I can fix it in one attempt.\n\nAcceptance criteria:\n- Rejection reason is specific, not 'document invalid'.\n- Re-upload returns to review without restarting the application.\n- Two rejections on the same document escalate to a human."),
            ],
        },
        {
            "title": "Transaction search and export",
            "goal": "Let merchants find any transaction in seconds and export what their accountant asks for.",
            "why": "Transaction search times out on merchants with more than 200k transactions, and CSV export is capped at 10k rows.",
            "metric": "p95 search latency under 800ms at 5M transactions; exports of any size complete asynchronously.",
            "discipline": "be",
            "components": ["search-index", "export-worker", "query-builder", "portal-bff"],
            "children": [
                ("story", "Full-text and faceted transaction search",
                 "As a merchant I want to search by reference, amount, card last four or customer email so I can answer a customer question while they are on the phone.\n\nAcceptance criteria:\n- Facets for status, scheme, currency and date range.\n- Results in under a second at the 95th percentile.\n- Searching an exact payment id always returns that payment first."),
                ("task", "Build and maintain the transaction search index",
                 "Index fed from the payment event stream. Reindexing from scratch must be possible without downtime."),
                ("story", "Asynchronous export with email delivery",
                 "As a merchant I want to export a year of transactions without the browser hanging so I can send it to my accountant.\n\nAcceptance criteria:\n- Export runs as a job; the user is emailed a signed download link.\n- Link expires after 7 days.\n- No row cap; a 2M row export must succeed."),
                ("task", "Saved search filters",
                 "Let merchants name and reuse a filter set. Shared across users in the same merchant account."),
                ("story", "Column selection and ordering for exports",
                 "As a finance user I want to choose which columns appear so the file matches my bookkeeping template.\n\nAcceptance criteria:\n- Column set persisted per user.\n- Ordering preserved in the generated file.\n- Currency amounts exported as decimal strings, never floats."),
                ("task", "Export rate limiting and abuse protection",
                 "One concurrent export per merchant account, ten per day. Exceeding it queues rather than fails."),
                ("task", "Deep-link a search result to the payment detail page",
                 "Filter state encoded in the URL so a merchant can send a colleague exactly what they are looking at."),
            ],
        },
        {
            "title": "Dashboard analytics revamp",
            "goal": "Replace the static dashboard with something a merchant can actually use to understand their business.",
            "why": "The dashboard is the most-visited page and the lowest-rated feature in the last two merchant surveys.",
            "metric": "Dashboard satisfaction from 2.8 to above 4.0; weekly active dashboard users up 50%.",
            "discipline": "fe",
            "components": ["analytics-api", "chart-library", "aggregation-worker", "dashboard-shell"],
            "children": [
                ("story", "Volume and revenue trend charts with comparison periods",
                 "As a merchant I want to compare this month against last month so I can tell whether things are improving.\n\nAcceptance criteria:\n- Comparison period selectable: previous period or same period last year.\n- Percentage change shown with direction.\n- Empty periods render as zero, not as a gap."),
                ("task", "Pre-aggregate daily metrics per merchant",
                 "Roll up volume, count, refunds, disputes and fees nightly plus an intraday partial. Live queries over raw payments do not scale past our largest merchants."),
                ("story", "Payment method and scheme breakdown",
                 "As a merchant I want to see which payment methods my customers use so I can decide what to enable.\n\nAcceptance criteria:\n- Breakdown by method, then by scheme within cards.\n- Long tail collapses into 'Other' with a hover breakdown.\n- Matches the transaction list totals exactly for the same period."),
                ("task", "Timezone-correct daily bucketing",
                 "Aggregate in the merchant's configured timezone. Today buckets by UTC, which is why merchants in Asia see the wrong daily totals."),
                ("story", "Decline reason insights",
                 "As a merchant I want to know why payments are declining so I can act on the ones I can influence.\n\nAcceptance criteria:\n- Declines grouped into actionable categories rather than raw issuer codes.\n- Each category links to guidance.\n- Insufficient funds and do-not-honour are distinguished."),
                ("task", "Dashboard skeleton loading and error states",
                 "Each widget loads and fails independently. One slow widget must not block the page."),
                ("task", "Chart accessibility: keyboard navigation and data table fallback",
                 "Every chart has an equivalent table view reachable by keyboard and announced by screen readers."),
                ("story", "Let merchants choose which widgets appear",
                 "As a merchant I want to hide widgets I do not care about so the page shows what matters to me.\n\nAcceptance criteria:\n- Widget visibility and order persisted per user.\n- A reset restores the default layout.\n- Layout survives a browser change because it is stored server-side."),
            ],
        },
        {
            "title": "Role-based access for merchant staff",
            "goal": "Let merchants delegate portal access safely instead of sharing one login.",
            "why": "Support sees shared credentials constantly. It is an audit risk and it makes every action unattributable.",
            "metric": "Shared-login support contacts down 90%; every portal action attributable to an individual user.",
            "discipline": "be",
            "components": ["auth-service", "permission-model", "invite-flow", "audit-log"],
            "children": [
                ("story", "Invite team members to a merchant account",
                 "As a merchant owner I want to invite my staff by email so they get their own login.\n\nAcceptance criteria:\n- Invite expires after 7 days and can be revoked.\n- Invitee sets their own password and second factor.\n- Pending invites are visible in the team list."),
                ("task", "Define the permission model and role presets",
                 "Presets: Owner, Admin, Finance, Support, Read-only. Permissions are the primitive; roles are just named bundles."),
                ("story", "Enforce permissions on every portal endpoint",
                 "As a security reviewer I need authorization enforced server-side so hiding a button is not the control.\n\nAcceptance criteria:\n- Every endpoint declares its required permission.\n- A missing declaration fails the build rather than defaulting to open.\n- Denials are logged with the actor and the permission required."),
                ("task", "Audit log of portal actions",
                 "Who did what, when, from where. Exportable, retained two years, and immutable from the application's perspective."),
                ("story", "Transfer account ownership",
                 "As a departing owner I want to hand ownership to a colleague so the account is not stranded.\n\nAcceptance criteria:\n- Transfer requires confirmation from both parties.\n- An account always has exactly one owner.\n- The transfer appears in the audit log."),
                ("task", "Session management and forced sign-out",
                 "List active sessions with device and location; allow revoking one or all. Revocation takes effect within 60 seconds."),
                ("task", "Migrate existing single-login accounts to the new model",
                 "Existing credential becomes the Owner user. No merchant should have to do anything for this to work."),
            ],
        },
        {
            "title": "Notification centre",
            "goal": "Give merchants one place to see what happened and control what reaches their inbox.",
            "why": "Notifications are scattered across four subsystems with no preferences, so merchants either drown or miss things that matter.",
            "metric": "Email unsubscribe rate down 60%; in-portal notification engagement above 40%.",
            "discipline": "fe",
            "components": ["notification-service", "preference-store", "email-renderer", "inbox-ui"],
            "children": [
                ("story", "In-portal notification inbox",
                 "As a merchant I want a single inbox of platform events so I can catch up after a few days away.\n\nAcceptance criteria:\n- Unread count in the header, cleared per notification not in bulk.\n- Grouped by day with infinite scroll.\n- Deep-links to the relevant payment, dispute or payout."),
                ("task", "Notification preference model per category and channel",
                 "Categories: payouts, disputes, security, product. Channels: email, in-portal, webhook. Security notifications cannot be disabled."),
                ("story", "Digest emails instead of per-event mail",
                 "As a high-volume merchant I want a daily summary so I am not sent hundreds of separate emails.\n\nAcceptance criteria:\n- Daily or weekly digest per category.\n- Digest sent in the merchant's timezone.\n- Nothing to report means no email at all."),
                ("task", "Consolidate the four existing notification senders",
                 "Payouts, disputes, onboarding and security each send mail their own way today. All four move behind the notification service."),
                ("task", "Templated, localised email rendering",
                 "One template system, previewable in the browser, with locale fallback to English rather than a blank section."),
                ("story", "Webhook channel for programmatic merchants",
                 "As a technically integrated merchant I want notifications delivered to my endpoint so I can react automatically.\n\nAcceptance criteria:\n- Signed payloads with a documented verification scheme.\n- Retries with exponential backoff for 24 hours.\n- Delivery attempts visible in the portal."),
            ],
        },
        {
            "title": "Responsive redesign and accessibility",
            "goal": "Make the portal usable on a phone and compliant with WCAG 2.2 AA.",
            "why": "38% of portal sessions are mobile against a layout designed for 1280px, and an enterprise prospect's procurement blocked on an accessibility audit.",
            "metric": "Zero critical or serious axe violations; mobile task completion parity with desktop.",
            "discipline": "design",
            "components": ["design-system", "layout-shell", "form-components", "navigation"],
            "children": [
                ("story", "Responsive navigation and app shell",
                 "As a merchant on a phone I want to reach every section without horizontal scrolling.\n\nAcceptance criteria:\n- Navigation collapses below 768px into a reachable menu.\n- Focus is trapped in the open menu and returns on close.\n- No page scrolls horizontally at 320px width."),
                ("task", "Audit the portal against WCAG 2.2 AA",
                 "Automated axe sweep plus manual keyboard and screen reader passes. Output is a prioritised ticket list, not a PDF."),
                ("task", "Fix colour contrast across the design system",
                 "Several semantic colours fail 4.5:1 on our background. Fix the tokens rather than the usages."),
                ("story", "Keyboard-navigable data tables",
                 "As a keyboard user I want to sort, page and open rows without a mouse.\n\nAcceptance criteria:\n- Every interactive cell is reachable in a sensible tab order.\n- Sort state announced to assistive technology.\n- A visible focus indicator on every focusable element."),
                ("task", "Accessible form error handling",
                 "Errors associated with their input, announced on submit, and summarised at the top of the form with links to each field."),
                ("story", "Responsive transaction list on mobile",
                 "As a merchant on a phone I want to scan transactions without pinching.\n\nAcceptance criteria:\n- Table becomes a card list below 768px.\n- The three fields merchants actually scan for stay visible.\n- Filters open in a sheet rather than a cramped dropdown."),
                ("task", "Respect prefers-reduced-motion across the portal",
                 "Disable non-essential transitions and animated chart entry when the user has asked for reduced motion."),
                ("task", "Document accessibility patterns in the design system",
                 "Each component documents its keyboard model and ARIA contract so the next component does not relitigate it."),
            ],
        },
        {
            "title": "Portal performance and reliability",
            "goal": "Make the portal fast on the pages merchants actually use, and stop the BFF being the weak link.",
            "why": "Largest Contentful Paint on the transaction list is 4.6s at the 75th percentile; the BFF times out under burst load.",
            "metric": "LCP under 2.5s at p75 on the top five pages; BFF error rate under 0.1%.",
            "discipline": "fe",
            "components": ["portal-bff", "bundle-pipeline", "cache-layer", "web-vitals"],
            "children": [
                ("task", "Instrument real user monitoring for Core Web Vitals",
                 "Field data per route, segmented by device class. Lab numbers have been misleading us."),
                ("story", "Code-split the portal bundle by route",
                 "As a merchant I want the page I opened to load without downloading the whole application.\n\nAcceptance criteria:\n- Each top-level route is its own chunk.\n- Initial JS under 200KB compressed.\n- Navigation between routes has no visible blank frame."),
                ("task", "Add response caching to the portal BFF",
                 "Cache read-heavy aggregate endpoints with explicit invalidation on the relevant events. No blind TTL on anything showing money."),
                ("task", "Fix N+1 queries on the transaction list endpoint",
                 "The endpoint issues one query per row for the customer and one for the payment method."),
                ("story", "Virtualised rendering for long lists",
                 "As a merchant with thousands of transactions I want scrolling to stay smooth.\n\nAcceptance criteria:\n- Only visible rows plus a buffer are in the DOM.\n- Keyboard navigation still reaches every row.\n- Scroll position restored when returning from a detail page."),
                ("task", "Set a performance budget in CI",
                 "Bundle size and Lighthouse thresholds fail the build. A budget nobody enforces is a wish."),
            ],
        },
    ],
}

# --- subtask templates ----------------------------------------------------

SUBTASKS = [
    ("Design the API contract", "Agree request and response shapes for {component} and land the OpenAPI change before implementation starts."),
    ("Implement the persistence layer", "Schema migration plus repository methods for {component}. Migration must be reversible."),
    ("Wire up the service layer", "Business logic in {service}, behind the feature flag so it can ship dark."),
    ("Add integration tests", "Cover the happy path plus the three failure modes we know about in {component}."),
    ("Update the OpenAPI spec and client", "Regenerate the client and check nothing downstream broke."),
    ("Add metrics and structured logging", "Counters, latency histogram and typed error logs for {component}."),
    ("Roll out behind a feature flag", "Flag default off, enable for internal accounts, then cohort by cohort."),
    ("Write the migration and backfill script", "Idempotent, resumable, and rate-limited so replica lag stays acceptable."),
    ("Update user-facing documentation", "Merchant-facing docs plus the internal runbook entry."),
    ("Handle the error and empty states", "Every failure mode in {component} needs a state a user can act on."),
    ("Add feature-flag cleanup ticket", "Remove {component} flag and dead branch once rollout hits 100%."),
    ("Review with security", "Threat model the {component} change and record the outcome on the ticket."),
]

# --- bug templates --------------------------------------------------------
# {component} and {service} come from the parent epic, so bugs stay on-topic.

BUGS = [
    ("{component} returns 500 when the request has no idempotency key",
     "Environment: production, observed on 2 of ~40k requests per hour.\n\nSteps to reproduce:\n1. POST to the {component} endpoint omitting the idempotency key header.\n2. Observe a 500 rather than a 400.\n\nExpected: a typed validation error naming the missing header.\nActual: NullPointerException in the handler, stack trace below.\n\n```\njava.lang.NullPointerException: Cannot invoke \"String.trim()\" because \"key\" is null\n\tat com.acme.{service}.IdempotencyFilter.doFilter(IdempotencyFilter.java:64)\n```\n\nImpact: merchants see an opaque error and retry, which is exactly what the missing key makes unsafe."),
    ("Duplicate records created when {component} retries after a timeout",
     "Environment: staging, reproduced 3 times out of 10.\n\nSteps to reproduce:\n1. Submit a request to {component}.\n2. Kill the downstream connection after the write but before the response.\n3. Client retries with the same idempotency key.\n\nExpected: the retry returns the original result.\nActual: a second record is created.\n\nThe idempotency check reads from the replica, so it misses a write that has not replicated yet."),
    ("{component} timezone handling produces off-by-one-day results",
     "Environment: production, affects merchants configured outside UTC.\n\nSteps to reproduce:\n1. Set the merchant timezone to Asia/Tokyo.\n2. Create a record at 08:00 local (23:00 UTC previous day).\n3. Filter for today in {component}.\n\nExpected: the record appears under today.\nActual: it appears under yesterday.\n\nThe boundary is computed in UTC and then formatted in local time, which is backwards."),
    ("Amounts lose precision in {component} for zero-decimal currencies",
     "Environment: production, JPY and KRW affected.\n\nSteps to reproduce:\n1. Process an amount of 1000 JPY through {component}.\n2. Inspect the stored value.\n\nExpected: 1000.\nActual: 10.00 — the value is divided by 100 unconditionally.\n\nThe minor-unit exponent is hardcoded to 2 instead of read from the currency."),
    ("{component} leaks connections under sustained load",
     "Environment: production, appears after roughly 6 hours of steady traffic.\n\nSymptom: the {service} connection pool saturates and requests queue until they time out. A restart clears it, which is how we have been surviving.\n\nThe error path in {component} does not close the connection; only the success path does."),
    ("Stale cache in {component} serves data from before the last update",
     "Environment: production, intermittent.\n\nSteps to reproduce:\n1. Update the underlying record.\n2. Read through {component} within about 30 seconds.\n\nExpected: the updated value.\nActual: the previous value.\n\nInvalidation is fired before the transaction commits, so the reload races ahead of the write."),
    ("Pagination in {component} skips records when data changes mid-scan",
     "Environment: production, visible on large result sets.\n\nSteps to reproduce:\n1. Start paging through {component} results.\n2. Have a new record inserted that sorts into an already-read page.\n3. Continue paging.\n\nExpected: stable pagination.\nActual: a record is skipped.\n\nOffset pagination over a mutating set; needs a keyset cursor."),
    ("{component} error message exposes internal identifiers to merchants",
     "Environment: production.\n\nThe validation failure returned from {component} includes the internal record id and the database constraint name. Merchants should get an actionable message and we should keep our schema to ourselves.\n\nFound during the pre-audit review."),
    ("Race condition in {component} when two updates land in the same second",
     "Environment: production, rare but reproducible under load.\n\nSteps to reproduce:\n1. Fire two concurrent updates for the same record through {component}.\n2. Inspect the result.\n\nExpected: last write wins, both recorded in history.\nActual: one update is silently lost.\n\nRead-modify-write with no optimistic locking."),
    ("{component} retries a permanently failed operation indefinitely",
     "Environment: production.\n\nA request rejected for a business reason is being retried as though it were a transient failure. One record has now been retried 14,000 times.\n\nRetry classification treats every non-2xx as retryable."),
    ("Sorting in {component} is case-sensitive and looks random to users",
     "Environment: production, cosmetic but reported repeatedly.\n\nExpected: alphabetical ordering a user would recognise.\nActual: uppercase entries sort before all lowercase ones.\n\nDatabase collation, not application logic."),
    ("{component} fails silently when the downstream returns 429",
     "Environment: production, during peak.\n\nExpected: back off and retry, or surface a typed rate-limit error.\nActual: the response is swallowed and the operation is marked successful.\n\nThe only reason we know is that the downstream's dashboard disagrees with ours."),
    ("Memory grows without bound in the {component} worker",
     "Environment: production, restarts required every 2 to 3 days.\n\nHeap dump shows a cache in {component} with no eviction policy holding roughly 400MB of records that will never be read again."),
    ("{component} rejects valid input containing non-ASCII characters",
     "Environment: production, affects merchants in several markets.\n\nSteps to reproduce:\n1. Submit a value containing accented or CJK characters to {component}.\n2. Observe rejection.\n\nExpected: accepted and stored correctly.\nActual: validation error citing an invalid character.\n\nThe validation regex is ASCII-only."),
    ("Deploy of {service} drops in-flight {component} work",
     "Environment: production, every deploy.\n\nExpected: graceful shutdown drains in-flight work.\nActual: the process exits immediately and work in progress is lost, then picked up late by the recovery job.\n\nNo shutdown hook; SIGTERM is not handled."),
]

# --- filler stories -------------------------------------------------------
# Used to pad a space up to the requested size. Deliberately generic in shape
# but parameterised by the epic's own component, so they still read as work
# that team would plausibly have on the board.

PAD_STORIES = [
    ("Add an audit trail to {component}",
     "As a compliance reviewer I want every change made through {component} recorded so I can answer 'who changed this' without asking an engineer.\n\nAcceptance criteria:\n- Actor, timestamp, before and after values captured.\n- Entries are immutable and retained per the data policy.\n- Visible to users with the audit permission, nobody else."),
    ("Support bulk operations in {component}",
     "As a high-volume user I want to act on many records at once so I am not clicking through them one at a time.\n\nAcceptance criteria:\n- Selection persists across pagination.\n- Partial failures report which records failed and why.\n- Bulk actions are rate-limited and audited."),
    ("Expose {component} health on the status page",
     "As a merchant I want to see whether {component} is degraded before I raise a ticket.\n\nAcceptance criteria:\n- Status reflects the real dependency, not just process liveness.\n- Incident history for the last 90 days.\n- Updated within 60 seconds of a state change."),
    ("Let users filter {component} by date range",
     "As a user I want to narrow {component} to a period so I can find what I need without scrolling.\n\nAcceptance criteria:\n- Presets for today, 7 days, 30 days, this month and custom.\n- Range respects the user's timezone.\n- Selected range is reflected in the URL."),
    ("Add pagination controls to the {component} list",
     "As a user I want to move through {component} results predictably.\n\nAcceptance criteria:\n- Keyset pagination so results stay stable while data changes.\n- Page size selectable from 25, 50, 100.\n- Total count shown, or an explicit 'many' when counting is too expensive."),
    ("Send a confirmation when a {component} action succeeds",
     "As a user I want confirmation that what I did worked so I am not left guessing.\n\nAcceptance criteria:\n- Inline confirmation with the affected record named.\n- Undo offered where the action is reversible.\n- Confirmation is announced to assistive technology."),
    ("Version the {component} API",
     "As an integrating developer I want a stable contract so my integration does not break when you ship.\n\nAcceptance criteria:\n- Version in the path, documented deprecation policy.\n- Old version supported for at least six months after deprecation.\n- Breaking changes require a new version, enforced by a contract test."),
    ("Add search to the {component} view",
     "As a user I want to search {component} rather than scan it.\n\nAcceptance criteria:\n- Matches on the identifiers users actually paste in.\n- Debounced, cancellable, and does not lose the previous result on a slow response.\n- Empty result state explains what was searched."),
    ("Let users export {component} data as CSV",
     "As a user I want the data in a spreadsheet so I can work with it in my own tools.\n\nAcceptance criteria:\n- Export reflects the filters currently applied.\n- Amounts exported as decimal strings, dates as ISO 8601.\n- Large exports run asynchronously."),
    ("Improve the {component} empty state",
     "As a first-time user I want the empty screen to tell me what to do next rather than just being blank.\n\nAcceptance criteria:\n- Explains why it is empty and the next action.\n- Distinguishes 'nothing yet' from 'nothing matched your filter'.\n- Same treatment applied everywhere {component} renders a list."),
    ("Add optimistic concurrency to {component} updates",
     "As a user I want to be told when someone else changed a record while I was editing it, rather than silently overwriting their work.\n\nAcceptance criteria:\n- Version token returned on read and required on write.\n- Conflict returns a typed error naming the fields that diverged.\n- The UI offers to reload rather than dropping the user's input."),
    ("Localise {component} for supported markets",
     "As a non-English-speaking user I want {component} in my language.\n\nAcceptance criteria:\n- All user-facing strings externalised, none concatenated.\n- Dates, numbers and currency formatted per locale.\n- Missing translations fall back to English rather than showing the key."),
]

# --- chore / tech-debt tasks ----------------------------------------------

CHORES = [
    ("Upgrade {service} to Spring Boot 3.4", "Routine dependency bump. Watch for the Jackson and Hibernate changes noted in the release notes."),
    ("Remove the {component} feature flag", "Rollout has been at 100% for four weeks. Delete the flag and the dead branch."),
    ("Add contract tests between {service} and its consumers", "Consumer-driven contracts so we stop breaking downstream services in staging."),
    ("Reduce {service} Docker image size", "Currently 1.1GB, mostly build tooling that has no business in the runtime layer."),
    ("Fix flaky {component} integration test", "Fails roughly 1 run in 12 in CI. It is a timing assumption, not a real bug, and people have started ignoring red builds."),
    ("Document the {component} architecture decision", "Write the ADR while the reasoning is still fresh."),
    ("Split the {service} god class", "One class is 2,400 lines and every change to it touches four unrelated features."),
    ("Add database index for the {component} hot query", "The query is a sequential scan over a table that has grown past 30M rows."),
    ("Migrate {component} logging to structured JSON", "Free-text logs cannot be queried, which is why every incident starts with grep."),
    ("Clean up unused {component} configuration properties", "Fourteen properties are defined and never read. They are actively misleading."),
]

# --- comments -------------------------------------------------------------
# Grouped by the moment they belong to, so the generator can attach them to a
# plausible point in the issue's timeline.

COMMENTS = {
    "triage": [
        "Reproduced on staging with the same payload. Adding the request id to the description.",
        "This has come in from support twice this week, both from merchants over 100k transactions/month. Bumping priority.",
        "I don't think this is {component} — the trace shows the failure upstream. Reassigning after I confirm.",
        "Duplicate of {key}? The symptom is the same but the trigger looks different, so leaving both open for now.",
        "Can we get the merchant id and timestamp? Without those I can't find the request in the logs.",
        "Confirmed this only happens on the retry path, which is why it looked intermittent.",
        "Not a regression — it's been broken since the {component} rewrite, we just had no alerting on it.",
    ],
    "planning": [
        "Sized this at 5 on the assumption we reuse the existing {component} client. If we have to write a new one it's more like 13.",
        "Splitting this: the API contract and the implementation are separate conversations and separate reviews.",
        "{actor} pointed out we need the migration in place first, so this depends on the backfill ticket.",
        "Pulling this into the sprint — it unblocks two other tickets and it's small.",
        "Deferring to next sprint. We don't have design sign-off and I'd rather not build it twice.",
        "Estimate is mostly test setup, not the change itself. The change is about thirty lines.",
        "Agreed scope in refinement: no {component} changes in this ticket, follow-up only.",
    ],
    "progress": [
        "Branch is up, working through the {component} edge cases. Nothing surprising yet.",
        "Hit a snag: the {service} test fixtures assume a single currency, so I'm rewriting those first.",
        "About 70% done. The remaining work is the error handling and the metrics.",
        "Rebased on main after the {component} refactor landed. Conflicts were mechanical.",
        "Local testing looks right. Deploying to staging this afternoon.",
        "Slower than estimated — the existing behaviour was undocumented and I've been reverse-engineering it.",
        "Paused on this to help with the incident. Picking it back up tomorrow.",
    ],
    "review": [
        "Left comments on the PR. Main one: the null check in {component} should be a validation at the boundary rather than a guard three layers deep.",
        "Looks good overall. Can we add a test for the concurrent case before this merges?",
        "Approved, but please add the metric before you deploy — we won't know if this works otherwise.",
        "I'd rather not add another config property here. Can this be derived from what we already know about the merchant?",
        "The migration isn't reversible as written. If we need to roll back at 2am we'll be in trouble.",
        "Nit: rename `handle` to something that says what it handles. Non-blocking.",
        "This changes the response shape, which is a breaking change for anyone parsing it strictly. Needs a version bump or a compatibility shim.",
    ],
    "blocked": [
        "Blocked on the acquirer sandbox being down. Ticket raised with them, no ETA yet.",
        "Waiting on {actor} for the design decision on the empty state before I build it.",
        "Blocked: needs the {component} migration deployed first, and that's stuck behind the release freeze.",
        "Blocked on legal signing off the data retention period. Pinged them Monday.",
        "Can't proceed without production access to confirm the data shape. Access request is in.",
        "Blocked on a credentials issue with the sandbox — reissued, waiting for propagation.",
    ],
    "qa": [
        "QA failed: the happy path works but the error state shows the raw error code instead of the message. Moving back to in progress.",
        "Verified on staging across Chrome, Firefox and Safari. Safari needed the extra fix from {key}, which is now merged.",
        "Tested with a merchant account holding 1.2M transactions — response times hold up. Passing.",
        "Found one edge case: zero-amount records render as blank rather than 0.00. Raised separately since it predates this change.",
        "Regression pass clean. No impact on the {component} flows.",
        "Can't verify — staging data doesn't include the currency I need. Asking for a seed.",
    ],
    "done": [
        "Deployed to production at 14:20. Metrics look normal, watching through tomorrow's peak.",
        "Rolled out to 100%. Closing this; the flag cleanup is tracked in a follow-up.",
        "Confirmed fixed in production — the error rate for {component} went to zero after the deploy.",
        "Merchant who reported this has confirmed it's resolved on their side.",
        "Shipped. One follow-up raised for the metrics gap {actor} spotted during review.",
        "Closing as done. The backfill finished overnight, 41M rows, no errors.",
    ],
    "carryover": [
        "Not finishing this sprint — the review found a design issue that needs another pass. Moving to next.",
        "Carrying over. Lost most of the sprint to the incident.",
        "Moving to the next sprint; the dependency landed too late for this one to be tested properly.",
        "Rolling over. It's close but I'd rather not merge something this size on the last day.",
    ],
}

# --- pull request titles --------------------------------------------------

PR_TITLES = [
    "feat({component}): {slug}",
    "fix({component}): {slug}",
    "refactor({component}): {slug}",
    "test({component}): cover {slug}",
    "chore({component}): {slug}",
]

BRANCH_PREFIXES = ["feature", "fix", "chore", "refactor"]

# --- labels ---------------------------------------------------------------
# V17 forbids type-shaped labels (bug/story/epic) — these are all cross-cutting.

LABELS = [
    "Feature", "Improvement", "Documentation", "Flagged", "tech-debt",
    "security", "performance", "compliance", "customer-reported",
    "needs-design", "migration", "observability", "accessibility",
    "regression", "quick-win",
]

SPRINT_GOALS = [
    "Ship {epic} behind a flag and validate it on internal accounts.",
    "Close out {epic} and start the {epic2} groundwork.",
    "Reduce {epic} risk before the compliance deadline; keep support load flat.",
    "Land the {epic} migration path so the cutover can start next sprint.",
    "Stabilise: clear the regression backlog and finish {epic}.",
    "Get {epic} in front of merchants, even partially, and learn from it.",
    "{epic} rollout to 50% plus the deferred work from last sprint.",
    "Foundation sprint for {epic} — contracts and migrations, little user-visible change.",
]
